/**
 * Knowledge Seed for Project ISA (ProRiv AS)
 * Contains actual domain findings, event storming models, competitor benchmarking,
 * architecture decisions, and open points to clarify with the Senior.
 * Complete bilingual support: German and Russian.
 */

import {
  TopicId,
  TopicContent,
  SeniorQuestion,
  ResearchFinding,
  CompetitorEntry,
  ProductRecommendation,
  OpenPoint,
  Decision,
  SeniorDecisionItem,
  DomainEventItem
} from '../types';

export const SEED_VERSION = 5;

export const MVP_STRATEGIC_STATEMENT = {
  quote: "Wir bauen kein zweites Dalux und kein neues Tripletex. Wir entwickeln eine schlanke Baustellen-Ausführungsschicht für ProRiv und integrieren bestehende Systeme.",
  quoteRu: "«Мы не создаем второй Dalux и не переписываем Tripletex. Мы разрабатываем удобный инструмент исполнения на стройплощадке для ProRiv и бесшовно интегрируем его с существующими системами.»",
  pilotScope: [
    "Wenige reale Mitarbeiter (Betonbohrer & Säger)",
    "Ein verantwortlicher Vorarbeiter",
    "Eine echte Baustelle (z. B. Kernbohr- & Sägeeinsatz)",
    "Begrenzte, definierte Arbeitsarten (Kernbohren, Wandsäge, Bodensäge)",
    "Plausible Zeiterfassung mit Clock-in Ausnahmebehandlung",
    "Ein vollständiger Arbeitsrapport von Erfassung bis Freigabe",
    "Prüfung der Übergabe an Tripletex (ERP-Schnittstelle)"
  ],
  pilotScopeRu: [
    "Несколько реальных рабочих (бурильщики и пильщики)",
    "Один ответственный бригадир",
    "Один реальный строительный объект (объект ProRiv)",
    "Ограниченный набор работ (алмазное бурение, нарезка швов, стенорезка)",
    "Прозрачный учет времени с обработкой исключений по GPS",
    "Один сквозной рапорт от стройплощадки до согласования",
    "Тестирование выгрузки данных в Tripletex ERP"
  ]
};

export const SENIOR_DECISION_QUESTIONS: SeniorDecisionItem[] = [
  {
    id: 'sd-1',
    number: 1,
    question: 'Welche Berechtigungen haben Arbeiter, Vorarbeiter und Büro endgültig?',
    questionRu: 'Какие окончательные права имеют рабочие, бригадиры и офис (матрица RBAC)?',
    responsiblePerson: 'Senior Software Engineer / Product Owner',
    priority: 'high',
    status: 'in_diskussion',
    currentProposal: 'Serverseitige RBAC-Matrix: Arbeiter erfassen Zeit und Rapport und senden den Rapport an Kunden; Vorarbeiter prüfen Stunden in Tripletex; Buchhaltung arbeitet dort. Wer Stammdaten verwaltet und ob ISA weitere Rollen braucht, ist offen.',
    currentProposalRu: 'Серверная матрица RBAC: Рабочие записывают время, рапорты и отправляют их клиенту; прораб проверяет часы в Tripletex; бухгалтерия работает там же. Дополнительные права ISA ещё открыты.',
    rationale: 'Ohne feste Berechtigungsmatrix können Sicherheitsregeln im Backend nicht implementiert werden. Unsichtbare Buttons im UI reichen nicht.',
    rationaleRu: 'Без фиксированной матрицы RBAC правила безопасности на бэкенде реализовать невозможно. Скрывать кнопки в интерфейсе недостаточно.',
    date: '2026-10-08',
    connectedTopics: ['users']
  },
  {
    id: 'sd-2',
    number: 2,
    question: 'Welche Felder sind je Arbeitsart (Kernbohren, Bodensäge, Wandsäge) verpflichtend?',
    questionRu: 'Какие поля обязательны для каждого типа работ (бурение, нарезка швов, стенорезка)?',
    responsiblePerson: 'Fachbereich ProRiv / Senior',
    priority: 'high',
    status: 'offen',
    currentProposal: 'Kernbohren: Durchmesser (mm), Bohrtiefe (cm), Anzahl, Ausrichtung (Wand/Decke/Überkopf). Sägen: Schnitttiefe (cm), Schnittlänge (m).',
    currentProposalRu: 'Алмазное бурение: диаметр (мм), глубина (см), кол-во, положение (стена/пол/потолок). Резка: глубина реза (см), длина (м).',
    rationale: 'Ermöglicht saubere Eingabemasken auf der Baustelle ohne Pflichtfeld-Überlastung des Arbeiters.',
    rationaleRu: 'Позволяет сделать удобные формы ввода на стройплощадке без перегрузки рабочего лишними обязательными полями.',
    date: '2026-10-08',
    connectedTopics: ['raport']
  },
  {
    id: 'sd-3',
    number: 3,
    question: 'Darf ein Mitarbeiter bei fehlendem oder ungenauem GPS-Signal einstempeln?',
    questionRu: 'Может ли рабочий отметить вход при отсутствии или неточности GPS-сигнала в подвале?',
    responsiblePerson: 'Senior Software Engineer / ProRiv GF',
    priority: 'high',
    status: 'in_diskussion',
    currentProposal: 'Ja, Einstempeln wird nicht blockiert, erzeugt jedoch ein "ClockInExceptionRecorded"-Event zur manuellen Prüfung durch den Vorarbeiter.',
    currentProposalRu: 'Да, чекин не блокируется, но генерируется событие ClockInExceptionRecorded для ручной проверки бригадиром.',
    rationale: 'Baustellen in Tiefgaragen, Kellern oder Betonschächten haben oft keinen GPS-Empfang. Blockieren würde die Arbeit aufhalten.',
    rationaleRu: 'На стройках в подземных паркингах, подвалах или шахтах спутники GPS часто недоступны. Блокировка остановила бы работу.',
    date: '2026-10-08',
    connectedTopics: ['vremya']
  },
  {
    id: 'sd-4',
    number: 4,
    question: 'Wer darf Arbeitszeiten und Sessions nachträglich korrigieren?',
    questionRu: 'Кто имеет право корректировать отработанное время и смены задним числом?',
    responsiblePerson: 'Senior Software Engineer',
    priority: 'medium',
    status: 'offen',
    currentProposal: 'Arbeiter vor der Einreichung; nach Einreichung nur Vorarbeiter/Büro mit dokumentiertem Änderungsgrund (Audit Trail).',
    currentProposalRu: 'Рабочий — до отправки на проверку. После отправки — только бригадир или офис с обязательным указанием причины (аудит-лог).',
    rationale: 'Verhindert unbemerkte Stundenmanipulationen und schützt die Nachvollziehbarkeit bei Lohnprüfung.',
    rationaleRu: 'Исключает незаметные манипуляции с часами и защищает юридическую прозрачность при начислении зарплаты.',
    date: '2026-10-08',
    connectedTopics: ['vremya', 'users']
  },
  {
    id: 'sd-5',
    number: 5,
    question: 'Wer darf Preise sehen und manuelle Preisänderungen (Overrides) vornehmen?',
    questionRu: 'Кто видит коммерческие цены и может делать ручные изменения тарифов (оверрайды)?',
    responsiblePerson: 'ProRiv Geschäftsleitung',
    priority: 'high',
    status: 'offen',
    currentProposal: 'Arbeiter sehen im MVP keine Preise. Vorarbeiter optional lesend. Nur Büro darf Preise anpassen oder Overrides definieren.',
    currentProposalRu: 'Рабочие в MVP цен не видят. Бригадир — опционально в режиме чтения. Только офис настраивает тарифы и оверрайды.',
    rationale: 'Auf der Baustelle steht die technische Mengenerfassung im Vordergrund, nicht die kaufmännische Preisfindung.',
    rationaleRu: 'На объекте рабочий должен фокусироваться на точных замерах объемов, а не на коммерческом ценообразовании.',
    date: '2026-10-08',
    connectedTopics: ['users', 'raport']
  },
  {
    id: 'sd-6',
    number: 6,
    question: 'Welche Preisregel hat Vorrang: Standard, Kunde, Projekt oder manueller Override?',
    questionRu: 'Какое правило цены имеет приоритет: стандарт, клиент, проект или ручной оверрайд?',
    responsiblePerson: 'Senior Architect / Fachbereich',
    priority: 'high',
    status: 'in_diskussion',
    currentProposal: 'Hierarchie: 1. Manueller Override (mit Begründung) > 2. Projektspezifischer Preis > 3. Kundenrahmenvertrag > 4. Standard-Preisliste.',
    currentProposalRu: 'Иерархия: 1. Ручной оверрайд (с обоснованием) > 2. Спеццена по проекту > 3. Рамочный договор клиента > 4. Стандартный прайс.',
    rationale: 'Eindeutige Rechenreihenfolge für den PriceSnapshot vor der Freigabe.',
    rationaleRu: 'Четкая очередность расчета для неизменяемого снимка цен PriceSnapshot перед утверждением.',
    date: '2026-10-08',
    connectedTopics: ['raport']
  },
  {
    id: 'sd-7',
    number: 7,
    question: 'Ist eine Kundenunterschrift für jeden Rapport und für den Stundenexport zwingend erforderlich?',
    questionRu: 'Обязательна ли подпись клиента для каждого рапорта и для экспорта часов в зарплату?',
    responsiblePerson: 'ProRiv Geschäftsleitung / Senior',
    priority: 'high',
    status: 'in_diskussion',
    currentProposal: 'Kundenantwort und Stundenexport als getrennte Prozesse darstellen. Die Pflicht, auf die Kundenantwort zu warten, ist noch offen. Arbeiter sendet Rapport direkt; Vorarbeiter prüft Stunden in Tripletex.',
    currentProposalRu: 'Ответ клиента и экспорт часов показывать отдельно. Нужно ли ждать клиента — открытый вопрос. Рабочий отправляет рапорт сам; прораб проверяет часы в Tripletex.',
    rationale: 'Bauleiter der Kunden sind oft nicht vor Ort. Ein Koppeln würde den internen Abrechnungsprozess blockieren.',
    rationaleRu: 'Прорабы клиентов часто отсутствуют на площадке. Жесткая привязка заблокировала бы начисление зарплаты в ProRiv.',
    date: '2026-10-08',
    connectedTopics: ['raport', 'api']
  },
  {
    id: 'sd-8',
    number: 8,
    question: 'Welche Daten sollen im MVP tatsächlich nach Tripletex übertragen werden?',
    questionRu: 'Какие именно данные передаем в Tripletex ERP в рамках MVP?',
    responsiblePerson: 'Senior Software Engineer / ERP-Spezialist',
    priority: 'high',
    status: 'in_diskussion',
    currentProposal: 'MVP-Fokus: erfasste Projektstunden mit Mitarbeiterbezug nach Tripletex übertragen; dort prüft der Vorarbeiter. PDF-Übertragung und API-Datenfelder noch technisch prüfen.',
    currentProposalRu: 'Фокус MVP: Подтвержденные часы с кодами сотрудника, проекта и активности (Timesheet Entry). Рапорты передаются ссылкой на PDF в S3.',
    rationale: 'Reduziert Integrationsrisiko. Tripletex-API-Limits für Binärdaten/Fotos müssen erst getestet werden.',
    rationaleRu: 'Снижает интеграционные риски и нагрузку на API Tripletex. Лимиты на бинарные файлы и фото требуют отдельного PoC.',
    date: '2026-10-08',
    connectedTopics: ['api']
  },
  {
    id: 'sd-9',
    number: 9,
    question: 'Welche Systeme sind für Kunden-, Projekt- und Aktivitätsstammdaten führend?',
    questionRu: 'Какая система является мастер-базой для клиентов, проектов и кодов активностей?',
    responsiblePerson: 'Senior Architect',
    priority: 'medium',
    status: 'in_diskussion',
    currentProposal: 'Tripletex ist Master für Kunden, Hauptprojekte und Aktivitäten. ISA führt Baustellen (Sites), Geofences und Rapportpositionen.',
    currentProposalRu: 'Tripletex — мастер-система для клиентов, главных проектов и кодов активностей. ISA ведет стройплощадки (Sites), геозоны и позиции рапортов.',
    rationale: 'Vermeidet doppelte Stammdatenpflege und Stammdaten-Inkonsistenzen in der Buchhaltung.',
    rationaleRu: 'Исключает дублирование справочников и рассинхронизацию с бухгалтерским учетом ProRiv.',
    date: '2026-10-08',
    connectedTopics: ['clients', 'api']
  },
  {
    id: 'sd-10',
    number: 10,
    question: 'Wie behandeln wir Korrekturen nach bereits erfolgter Freigabe oder ERP-Export?',
    questionRu: 'Как обрабатывать корректировки после уже выполненного утверждения или экспорта в ERP?',
    responsiblePerson: 'Senior Software Engineer',
    priority: 'high',
    status: 'offen',
    currentProposal: 'Freigegebene Objekte werden nicht mutiert, sondern erzeugen eine versionierte Revision (WorkReportRevision) mit Storno-/Nachbuchungsmuster.',
    currentProposalRu: 'Утвержденные объекты не перезаписываются, а создают версионированную ревизию (WorkReportRevision) по принципу сторно/доп.проводки.',
    rationale: 'Auditierbarkeit und Verhinderung von asynchronen Doppelbuchungen in Tripletex.',
    rationaleRu: 'Обеспечивает полный аудит и исключает случайные дублированные проводки в Tripletex.',
    date: '2026-10-08',
    connectedTopics: ['raport', 'api', 'vremya']
  }
  ,{
    id: 'sd-11-hms-role',
    number: 11,
    question: 'In welcher Rolle arbeitet ProRiv auf Baustellen (Subunternehmer / Hauptunternehmer / Bauherr)? Wer führt die elektronische HMS-Übersichtsliste, und braucht ISA dafür überhaupt eine eigene Funktion?',
    questionRu: 'В какой роли ProRiv работает на стройках (субподрядчик / генподрядчик / заказчик строительства)? Кто ведёт обязательный электронный список HMS и нужна ли вообще такая функция в ISA?',
    responsiblePerson: 'Senior Software Engineer + Isa / ProRiv Geschäftsleitung',
    priority: 'high',
    status: 'offen',
    currentProposal: 'MVP: Keine eigene gesetzliche Anwesenheitsliste entwickeln, solange Baustellenverantwortung und bestehende Systeme ungeklärt sind. ISA erfasst zunächst interne Projektzeiten (Beginn, Ende, Pausen); HMS-Kartennummer nur bei nachgewiesenem Zweck/datenschutzkonform speichern. Wenn ProRiv die Listenführung übernimmt oder Baustellen einen Export verlangen, Schnittstelle bzw. passende Listenfunktion getrennt bewerten. Interne Zeitbuchungen ersetzen die gesetzliche Liste nicht.',
    currentProposalRu: 'MVP: Не строить отдельный обязательный реестр, пока неизвестны ответственность и существующие системы на стройках. В ISA сначала учитывать часы по проектам (начало, конец, перерывы); номер HMS-карты хранить только при обоснованной цели и соблюдении защиты данных. При поручении вести список или требовании передачи данных отдельно оценить интеграцию либо функцию реестра. Учёт часов не заменяет обязательный список.',
    rationale: 'Nach Byggherreforskriften § 15 liegt die Verantwortung grundsätzlich beim Bauherrn; Listenführung kann schriftlich delegiert werden (oft an den Hauptunternehmer). Daher genügt die Unterscheidung Haupt-/Subunternehmer allein nicht. Bedarf mit Isa bestätigen; nicht voreilig ein separates HMS-Modul bauen. Quelle: https://www.arbeidstilsynet.no/hms/hms-i-bygg-og-anlegg/byggherreforskriften/elektroniske-oversiktslister/',
    rationaleRu: 'По § 15 Byggherreforskriften ответственность обычно у заказчика строительства (byggherre); ведение списка можно письменно передать другой фирме, часто генподрядчику. Статус субподрядчика или генподрядчика сам по себе недостаточен; уточнить у Исы.',
    date: '2026-10-09',
    connectedTopics: ['vremya', 'users', 'clients', 'api']
  }
];\n\nexport const DOMAIN_EVENTS_LIST: DomainEventItem[] = [
  {
    id: 'de-1',
    name: 'WorkSessionStarted',
    category: 'Session & Zeit',
    categoryRu: 'Сессии и время',
    description: 'Arbeiter stempelt auf Baustelle ein. Zeitstempel und GPS-Messung werden erfasst.',
    descriptionRu: 'Рабочий отмечает начало смены на стройплощадке. Фиксируются метка времени и GPS-координаты.',
    command: 'StartWorkSession',
    aggregate: 'WorkSession',
    readModel: 'ActiveSessionsPerSite',
    policyOrRule: 'Plausibilitätsprüfung gegen Site-Geofence',
    policyOrRuleRu: 'Проверка правдоподобия относительно геозоны площадки',
    openDecision: 'Blockieren oder Warnung bei Geofence-Abweichung?',
    openDecisionRu: 'Блокировать или выдавать предупреждение при несовпадении геозоны?'
  },
  {
    id: 'de-2',
    name: 'ClockInExceptionRecorded',
    category: 'Session & Zeit',
    categoryRu: 'Сессии и время',
    description: 'Ausnahme erfasst: GPS fehlt, ungenau (>100m) oder außerhalb des Geofence.',
    descriptionRu: 'Зафиксировано исключение: нет GPS, погрешность >100м или координаты вне геозоны.',
    command: 'RecordClockInException',
    aggregate: 'WorkSession',
    readModel: 'ForemanReviewQueue',
    policyOrRule: 'Ausnahme wird dem Vorarbeiter zur manuellen Sichtung markiert',
    policyOrRuleRu: 'Исключение помечается в очереди бригадира для ручной проверки',
    openDecision: 'Toleranzradius für Baustellen-Geofence festlegen',
    openDecisionRu: 'Установить радиус допуска для геозоны стройплощадки'
  },
  {
    id: 'de-3',
    name: 'WorkSessionStopped',
    category: 'Session & Zeit',
    categoryRu: 'Сессии и время',
    description: 'Arbeiter beendet Arbeitssitzung. Bruttozeit wird berechnet.',
    descriptionRu: 'Рабочий завершает смену. Рассчитывается общее время присутствия (брутто).',
    command: 'StopWorkSession',
    aggregate: 'WorkSession',
    readModel: 'DailyWorkerSessionSummary',
    policyOrRule: 'Erzeugt Vorschlag für TimesheetEntry',
    policyOrRuleRu: 'Формирует проект записи табеля рабочего времени (TimesheetEntry)',
    openDecision: 'Automatische Pausenabzüge definieren',
    openDecisionRu: 'Определить правила автоматического вычета перерывов'
  },
  {
    id: 'de-4',
    name: 'TimesheetSubmitted',
    category: 'Session & Zeit',
    categoryRu: 'Сессии и время',
    description: 'Arbeitszeiteintrag wird zur Prüfung an den Vorarbeiter eingereicht.',
    descriptionRu: 'Запись рабочего времени отправляется на проверку бригадиру.',
    command: 'SubmitTimesheet',
    aggregate: 'TimesheetEntry',
    readModel: 'PendingTimesheetApprovals',
    policyOrRule: 'Arbeiter kann Zeit nicht mehr direkt bearbeiten',
    policyOrRuleRu: 'Рабочий больше не может редактировать часы напрямую',
    openDecision: 'Frist für wöchentliche Zeiteinreichung',
    openDecisionRu: 'Срок еженедельной подачи табелей'
  },
  {
    id: 'de-5',
    name: 'TimesheetCorrectionRequested',
    category: 'Session & Zeit',
    categoryRu: 'Сессии и время',
    description: 'Vorarbeiter fordert Korrektur an (z. B. unklare Reisezeit oder Abweichung).',
    descriptionRu: 'Бригадир запрашивает правку (неясное время на дорогу или нестыковка).',
    command: 'RequestTimesheetCorrection',
    aggregate: 'TimesheetEntry',
    readModel: 'WorkerCorrectionTasks',
    policyOrRule: 'Status wechselt auf CorrectionRequested, Kommentar ist Pflicht',
    policyOrRuleRu: 'Статус меняется на CorrectionRequested, комментарий обязателен',
    openDecision: 'Darf Vorarbeiter Zeiten direkt überschreiben?',
    openDecisionRu: 'Может ли бригадир править часы напрямую?'
  },
  {
    id: 'de-6',
    name: 'TimesheetApproved',
    category: 'Session & Zeit',
    categoryRu: 'Сессии и время',
    description: 'Vorarbeiter gibt Arbeitsstunden fachlich frei.',
    descriptionRu: 'Бригадир утверждает отработанные часы.',
    command: 'ApproveTimesheet',
    aggregate: 'TimesheetEntry',
    readModel: 'ApprovedHoursForExport',
    policyOrRule: 'Stunden sind bereit für Tripletex-Warteschlange',
    policyOrRuleRu: 'Часы готовы к отправке в очередь Tripletex',
    openDecision: 'Zusätzliche Büro-Zweitfreigabe erforderlich?',
    openDecisionRu: 'Требуется ли дополнительное согласование офисом?'
  },
  {
    id: 'de-7',
    name: 'WorkReportCreated',
    category: 'Rapport & Aufmaß',
    categoryRu: 'Рапорты и замеры',
    description: 'Arbeitsrapport mit Projekt, Baustelle und Datum initialisiert.',
    descriptionRu: 'Создан рабочий рапорт с привязкой к проекту, площадке и дате.',
    command: 'CreateWorkReport',
    aggregate: 'WorkReport',
    readModel: 'DraftReportsList',
    policyOrRule: 'Eindeutige Client-generierte UUID für Offline-Fähigkeit',
    policyOrRuleRu: 'Клиентский UUID для полной работы оффлайн',
    openDecision: 'Kopplung mit aktiver WorkSession als Vorschlag',
    openDecisionRu: 'Автоматическая подвязка активной смены в качестве предложения'
  },
  {
    id: 'de-8',
    name: 'WorkReportSubmitted',
    category: 'Rapport & Aufmaß',
    categoryRu: 'Рапорты и замеры',
    description: 'Rapport mit erfassten Bohr-/Sägemengen und Fotos eingereicht.',
    descriptionRu: 'Рапорт с внесенными объемами бурения/резки и фото отправлен на проверку.',
    command: 'SubmitWorkReport',
    aggregate: 'WorkReport',
    readModel: 'ForemanReportReviewQueue',
    policyOrRule: 'Mindestens eine Position und Plausibilitätscheck erforderlich',
    policyOrRuleRu: 'Обязательно наличие хотя бы одной позиции и проверка объемов',
    openDecision: 'Fotopflicht für Bohrungen oder Regiearbeiten?',
    openDecisionRu: 'Обязательно ли фото для бурения или почасовых допработ?'
  },
  {
    id: 'de-9',
    name: 'WorkReportCorrectionRequested',
    category: 'Rapport & Aufmaß',
    categoryRu: 'Рапорты и замеры',
    description: 'Vorarbeiter oder Büro beanstandet Maße oder fehlende Angaben.',
    descriptionRu: 'Бригадир или офис отклоняет рапорт из-за неверных замеров или нехватки данных.',
    command: 'RequestReportCorrection',
    aggregate: 'WorkReport',
    readModel: 'WorkerReportRevisions',
    policyOrRule: 'Rapport geht zurück an Ersteller mit Änderungshinweis',
    policyOrRuleRu: 'Рапорт возвращается автору с указанием необходимых правок',
    openDecision: 'Wer darf Korrekturen bei abwesendem Arbeiter vornehmen?',
    openDecisionRu: 'Кто может вносить правки, если рабочий на больничном или в отпуске?'
  },
  {
    id: 'de-10',
    name: 'WorkReportApproved',
    category: 'Rapport & Aufmaß',
    categoryRu: 'Рапорты и замеры',
    description: 'HYPOTHETISCHER ALTER ENTWURF: Vorarbeiterfreigabe des Rapports (vom Kundengespräch nicht bestätigt; Arbeiter sendet direkt).',
    descriptionRu: 'СТАРЫЙ НЕПОДТВЕРЖДЁННЫЙ ВАРИАНТ: прораб утверждает рапорт. По разговору рабочий отправляет его сам.',
    command: 'ApproveWorkReport',
    aggregate: 'WorkReport',
    readModel: 'ApprovedReportsOverview',
    policyOrRule: 'Gibt Rapport für Kunden-Review und Büro-Pricing frei',
    policyOrRuleRu: 'Открывает рапорт для согласования клиентом и расчета офисом',
    openDecision: 'Automatische Benachrichtigung an Büro',
    openDecisionRu: 'Автоматическое уведомление офиса'
  },
  {
    id: 'de-11',
    name: 'PriceSnapshotLocked',
    category: 'Preis & Kunde',
    categoryRu: 'Цены и клиенты',
    description: 'Preise, Zuschläge und Rabatte werden unveränderlich fixiert.',
    descriptionRu: 'Цены, надбавки и скидки фиксируются без возможности скрытого изменения.',
    command: 'LockPriceSnapshot',
    aggregate: 'WorkReport',
    readModel: 'BilledReportsList',
    policyOrRule: 'Preis darf nicht mehr dynamisch nachberechnet werden',
    policyOrRuleRu: 'Итоговые тарифы замораживаются в неизменяемый снимок (Snapshot)',
    openDecision: 'Genaue Hierarchie der Preislistenregeln',
    openDecisionRu: 'Иерархия приоритетов прайс-листов'
  },
  {
    id: 'de-12',
    name: 'CustomerReviewLinkSent',
    category: 'Preis & Kunde',
    categoryRu: 'Цены и клиенты',
    description: 'Zeitlich begrenzter Magic Link wird an Kundenkontakt per SMS/Mail gesendet.',
    descriptionRu: 'Временная ссылка (Magic Link) отправлена контактному лицу клиента по SMS/Mail.',
    command: 'SendCustomerReviewLink',
    aggregate: 'WorkReport',
    readModel: 'CustomerPendingReviews',
    policyOrRule: 'Token läuft nach X Tagen ab, kein permanentes Kundenkonto nötig',
    policyOrRuleRu: 'Ссылка действует X дней, постоянный логин клиенту не требуется',
    openDecision: 'Gültigkeitsdauer des Links (z. B. 7 oder 14 Tage)',
    openDecisionRu: 'Срок действия ссылки (например, 7 или 14 дней)'
  },
  {
    id: 'de-13',
    name: 'CustomerReportConfirmed',
    category: 'Preis & Kunde',
    categoryRu: 'Цены и клиенты',
    description: 'Kunde öffnet Link und bestätigt ausgeführte Arbeiten.',
    descriptionRu: 'Клиент переходит по ссылке и подтверждает выполненный объем.',
    command: 'ConfirmReportByCustomer',
    aggregate: 'WorkReport',
    readModel: 'CustomerConfirmedReports',
    policyOrRule: 'Zeitstempel, IP und Bestätigungsflag werden dokumentiert',
    policyOrRuleRu: 'Фиксируются метка времени, IP-адрес и факт согласования',
    openDecision: 'Reicht einfache Bestätigung oder digitale Signatur?',
    openDecisionRu: 'Достаточно ли кнопки подтверждения или нужна цифровая подпись пальцем?'
  },
  {
    id: 'de-14',
    name: 'CustomerReportSigned',
    category: 'Preis & Kunde',
    categoryRu: 'Цены и клиенты',
    description: 'Kunde leistet digitale Unterschrift auf dem mobilen Gerät oder im Web.',
    descriptionRu: 'Клиент расписывается на экране устройства или на веб-странице.',
    command: 'SignReportByCustomer',
    aggregate: 'WorkReport',
    readModel: 'SignedReportsArchive',
    policyOrRule: 'Signatur-Bitmap wird gesichert in S3 abgelegt',
    policyOrRuleRu: 'Изображение подписи безопасно сохраняется в S3',
    openDecision: 'Unterschrift vor Ort auf Arbeiter-Gerät vs. Web-Link',
    openDecisionRu: 'Подпись на устройстве рабочего vs онлайн по ссылке'
  },
  {
    id: 'de-15',
    name: 'CustomerReportRejected',
    category: 'Preis & Kunde',
    categoryRu: 'Цены и клиенты',
    description: 'Kunde lehnt Rapport oder einzelne Mengen ab mit Begründung.',
    descriptionRu: 'Клиент отклоняет рапорт или спорные позиции с указанием причины.',
    command: 'RejectReportByCustomer',
    aggregate: 'WorkReport',
    readModel: 'DisputedReportsQueue',
    policyOrRule: 'Warnung an Büro & Vorarbeiter; Klärungsfall eröffnet',
    policyOrRuleRu: 'Оповещение офиса и бригадира; создается спорный случай',
    openDecision: 'Teilfreigabe einzelner Positionen zulassen?',
    openDecisionRu: 'Разрешить частичное согласование бесспорных позиций?'
  },
  {
    id: 'de-16',
    name: 'TripletexExportQueued',
    category: 'ERP & Tripletex',
    categoryRu: 'ERP и Tripletex',
    description: 'Freigegebener Datensatz wird in die Export-Warteschlange eingereiht.',
    descriptionRu: 'Согласованная запись поставлена в очередь экспорта в Tripletex.',
    command: 'QueueTripletexExport',
    aggregate: 'IntegrationJob',
    readModel: 'ExportMonitoringDashboard',
    policyOrRule: 'Idempotenz-Schlüssel wird vergeben',
    policyOrRuleRu: 'Присваивается ключ идемпотентности (Idempotency Key)',
    externalSystem: 'Tripletex API',
    openDecision: 'Sofortiger Export vs. nächtlicher Batch-Lauf',
    openDecisionRu: 'Мгновенная отправка или ночной пакетный запуск?'
  },
  {
    id: 'de-17',
    name: 'TripletexExportSucceeded',
    category: 'ERP & Tripletex',
    categoryRu: 'ERP и Tripletex',
    description: 'Tripletex bestätigt erfolgreiche Übernahme der Stunden/Daten.',
    descriptionRu: 'Tripletex подтверждает успешный прием часов и данных.',
    command: 'CompleteTripletexExport',
    aggregate: 'IntegrationJob',
    readModel: 'SynchronizedRecords',
    policyOrRule: 'Externe Tripletex-ID wird auf Datensatz gespeichert',
    policyOrRuleRu: 'Внешний идентификатор Tripletex ID сохраняется в ISA',
    externalSystem: 'Tripletex API',
    openDecision: 'Welche Rückmeldedaten in ISA persistiert werden',
    openDecisionRu: 'Какие данные ответа Tripletex сохранять в базе ISA'
  },
  {
    id: 'de-18',
    name: 'TripletexExportFailed',
    category: 'ERP & Tripletex',
    categoryRu: 'ERP и Tripletex',
    description: 'Export schlägt fehl (Netzwerk, Token ungültig, Validierungsfehler).',
    descriptionRu: 'Ошибка экспорта (сбой сети, истек токен, ошибка валидации).',
    command: 'FailTripletexExport',
    aggregate: 'IntegrationJob',
    readModel: 'FailedExportsAlerts',
    policyOrRule: 'Fachliche Freigabe bleibt bestehen! Retry-Mechanismus greift',
    policyOrRuleRu: 'Согласование бригадиром НЕ отменяется! Срабатывает повтор (Retry)',
    externalSystem: 'Tripletex API',
    openDecision: 'Automatischer Retry-Intervall und Alarmierung',
    openDecisionRu: 'Интервал повторов и отправка алертов разработчикам'
  }
];

export const INITIAL_COMPETITORS: CompetitorEntry[] = [
  {
    id: 'comp-smartdok',
    topicId: 'vremya',
    additionalTopicIds: ['users', 'clients'],
    productName: 'SmartDok',
    analyzedFeature: 'Baustellenzeiterfassung, Vorarbeiter-Freigaben, Geofencing',
    analyzedFeatureRu: 'Учет времени на стройке, согласование бригадиром, геозоны',
    investigationGoal: 'Wie löst der norwegische Marktführer Zeiterfassung und Geofences auf Baustellen?',
    investigationGoalRu: 'Как норвежский лидер рынка решает учет времени и геозоны на стройплощадках?',
    observedWorkflow: 'Arbeiter stempelt via mobiler App ein; Vorarbeiter sieht Mannschaftsübersicht; Geofence validiert Einsatzort; Freigabepfad vor Lohnexport.',
    observedWorkflowRu: 'Рабочий чекинится в приложении; бригадир видит общую панель бригады; геозона проверяет объект; этап согласования перед зарплатой.',
    keyTakeaway: 'Vorbild für norwegische Baustellenprozesse. Getrennte Ansichten für Arbeiter und Vorarbeiter schaffen Klarheit.',
    keyTakeawayRu: 'Эталон для норвежских строительных процессов. Раздельные экраны для рабочего и бригадира дают максимальную прозрачность.',
    disadvantages: 'Umfangreiches Großsystem, für reine Bohr- & Sägespezialisten oft überdimensioniert und teuer.',
    disadvantagesRu: 'Громоздкая система "все-в-одном", для узкоспециализированных бурильщиков и пильщиков слишком сложна и дорога.',
    sourceOrLink: '',
    transferability: 'Sehr hoch für den Session-Ablauf und die Geofence-Plausibilisierung in ISA.',
    transferabilityRu: 'Очень высокая: переносим разделение смен и проверку геозон в архитектуру ISA.',
    origin: 'competitor_research',
    status: 'externally_unverified',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },
  {
    id: 'comp-finkzeit',
    topicId: 'vremya',
    additionalTopicIds: ['raport'],
    productName: 'FinkZeit',
    analyzedFeature: 'Trennung von Arbeitszeit, Auftragszeit und Tätigkeiten',
    analyzedFeatureRu: 'Разделение рабочего времени смены, времени заказа и конкретных операций',
    investigationGoal: 'Wie wird Anwesenheitszeit sauber von produktiver Auftragszeit getrennt?',
    investigationGoalRu: 'Как чисто отделить общее время присутствия на смене от продуктивного времени по заказу?',
    observedWorkflow: 'Einstempeln in Tagesschicht, anschließendes Zuordnen von Tätigkeiten (Bohren, Sägen, Rüstzeit, Reisetid).',
    observedWorkflowRu: 'Отметка входа на дневную смену, затем распределение операций (бурение, пила, подготовка, время в пути).',
    keyTakeaway: 'Strikte Trennung von Anwesenheit (WorkSession) und Auftragsaufwand (Timesheet/Report) verhindert Abrechnungsfehler.',
    keyTakeawayRu: 'Строгое разделение смены (WorkSession) и трудозатрат по заказу (Timesheet/Report) предотвращает ошибки расчета.',
    disadvantages: 'Kann zu höherem Erfassungsaufwand führen, wenn Arbeiter jeden Teilschritt einzeln erfassen müssen.',
    disadvantagesRu: 'Может перегрузить рабочего, если заставлять кликать каждый шаг отдельно.',
    sourceOrLink: '',
    transferability: 'Architektonisches Leitbild für unsere Datenmodelltrennung in ISA.',
    transferabilityRu: 'Архитектурный фундамент для разделения наших моделей данных в ISA.',
    origin: 'competitor_research',
    status: 'externally_unverified',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },
  {
    id: 'comp-qbtime',
    topicId: 'vremya',
    additionalTopicIds: ['users'],
    productName: 'QuickBooks Time',
    analyzedFeature: 'GPS-Zeiterfassung und dokumentierte Ausnahmebehandlung',
    analyzedFeatureRu: 'GPS-учет времени и регламентированная обработка исключений',
    investigationGoal: 'Wie geht das System mit fehlerhaftem oder verweigertem GPS-Signal um?',
    investigationGoalRu: 'Как система поступает при сбое или отсутствии сигнала GPS?',
    observedWorkflow: 'Clock-in erfolgt mit Standortabgleich; bei Signalverlust oder Distanz zum Geofence wird Eintrag mit Flag markiert, aber nicht blockiert.',
    observedWorkflowRu: 'Отметка сверяет координаты; при потере спутника или отклонении запись получает флаг исключения, но не блокирует работу.',
    keyTakeaway: 'Niemals den Arbeiter vor Ort blockieren. Ausnahmen als Prüfaufgabe für den Vorarbeiter markieren.',
    keyTakeawayRu: 'Никогда не блокировать рабочего на объекте. Оформлять отклонения как задачу на проверку бригадиру.',
    disadvantages: 'In Europa datenschutzrechtlich sensibel bei permanentem Tracking.',
    disadvantagesRu: 'В Европе постоянный трекинг юридически чувствителен и нарушает регламенты приватности.',
    sourceOrLink: '',
    transferability: 'Exakt dieses Ausnahmemuster (ClockInExceptionRecorded) übernehmen wir für ProRiv.',
    transferabilityRu: 'Именно этот паттерн (ClockInExceptionRecorded) берем для ProRiv.',
    origin: 'competitor_research',
    status: 'externally_unverified',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },
  {
    id: 'comp-dalux',
    topicId: 'mobile-app',
    additionalTopicIds: ['raport'],
    productName: 'Dalux',
    analyzedFeature: 'Offline-Baustellenarbeit, Foto-Dokumentation und Pläne',
    analyzedFeatureRu: 'Оффлайн-работа на стройке, фотодокументация и чертежи',
    investigationGoal: 'Wie stabil sind Offline-Dokumentation und Medien-Uploads unter realen Baustellenbedingungen?',
    investigationGoalRu: 'Насколько надежны оффлайн-сохранение и загрузка медиафайлов в реальных условиях стройки?',
    observedWorkflow: 'Lokale Speicherung von Aufgaben und Fotos auf dem Endgerät; asynchrone Warteschlange bei Wiederverbindung.',
    observedWorkflowRu: 'Локальное сохранение данных и фото в базе устройства; асинхронная очередь синхронизации при появлении сети.',
    keyTakeaway: 'Offline-First ist für Baustellen essenziell. Uploads müssen im Hintergrund mit Fortschrittsanzeige laufen.',
    keyTakeawayRu: 'Offline-First критически важен. Загрузка фото должна идти в фоне с понятным статусом.',
    disadvantages: 'Sehr komplex, Fokus liegt auf 3D/BIM und großen Generalunternehmern.',
    disadvantagesRu: 'Очень сложный монструозный интерфейс, фокус на 3D/BIM и генподрядчиков.',
    sourceOrLink: '',
    transferability: 'Für ISA übernehmen wir das robuste lokale Queue-Muster (SQLite + S3 Uploads).',
    transferabilityRu: 'Для ISA берем паттерн надежной локальной очереди (SQLite + прямые загрузки в S3).',
    origin: 'competitor_research',
    status: 'externally_unverified',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },
  {
    id: 'comp-planradar',
    topicId: 'raport',
    additionalTopicIds: ['mobile-app'],
    productName: 'PlanRadar',
    analyzedFeature: 'Strukturierte mobile Formulare und Baudokumentation',
    analyzedFeatureRu: 'Структурированные мобильные формы и строительная документация',
    investigationGoal: 'Wie werden spezifische Handwerkerberichte mobil und touch-optimiert erfasst?',
    investigationGoalRu: 'Как специализированные отчеты мастеров оптимизируются под сенсорные экраны?',
    observedWorkflow: 'Vordefinierte Auswahllisten, Pflichtfelder für Maße und direkte Kamera-Anbindung mit Annotationen.',
    observedWorkflowRu: 'Готовые списки выбора, обязательные поля для размеров и быстрая фотокамера.',
    keyTakeaway: 'Formulare müssen extrem simpel mit großen Touch-Zielen für Handschuhe/Baustelle gestaltet sein.',
    keyTakeawayRu: 'Формы должны быть предельно простыми, с крупными кнопками под работу в перчатках на объекте.',
    disadvantages: 'Eigenständiges Ticketsystem, keine native Integration in norwegische Lohn- und ERP-Systeme wie Tripletex.',
    disadvantagesRu: 'Изолированная тикет-система, нет нативной связки с норвежской зарплатной ERP Tripletex.',
    sourceOrLink: '',
    transferability: 'Gestaltung der Kernbohr- und Sägemasken in React Native.',
    transferabilityRu: 'Дизайн экранов замеров бурения и резки в React Native.',
    origin: 'competitor_research',
    status: 'externally_unverified',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },
  {
    id: 'comp-fieldwire',
    topicId: 'raport',
    additionalTopicIds: ['clients'],
    productName: 'Fieldwire',
    analyzedFeature: 'Baustellenaufgaben und schnelle Felderfassung',
    analyzedFeatureRu: 'Строительные задачи и быстрый выбор объекта',
    investigationGoal: 'Wie gelingt eine intuitive Projekt- und Aufgabenwahl für gewerbliche Mitarbeiter?',
    investigationGoalRu: 'Как реализовать понятный выбор проекта и площадки для рабочих?',
    observedWorkflow: 'Schnellauswahl aus Projektliste, Zuordnung von Einsatzberichten und Statusanzeige.',
    observedWorkflowRu: 'Быстрый выбор из списка проектов, привязка рапортов и наглядный статус.',
    keyTakeaway: 'Arbeiter muss mit maximal zwei Klicks sein Projekt und die Baustelle auswählen können.',
    keyTakeawayRu: 'Рабочий должен выбирать свой объект максимум за два клика.',
    disadvantages: 'Starker US-Fokus, wenig Bezug zu norwegischen Gewerken und Regieabrechnungen.',
    disadvantagesRu: 'Сильный уклон в стандарты США, слабая связь со спецификой норвежских подрядчиков.',
    sourceOrLink: '',
    transferability: 'Führung des Arbeiters im UI: Schnellauswahl der Baustelle.',
    transferabilityRu: 'Навигация рабочего в интерфейсе: быстрый выбор стройплощадки.',
    origin: 'competitor_research',
    status: 'externally_unverified',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },
  {
    id: 'comp-tripletex',
    topicId: 'api',
    additionalTopicIds: ['clients', 'vremya'],
    productName: 'Tripletex',
    analyzedFeature: 'ERP, Projekte, Aktivitäten, Zeiterfassung und Buchhaltung',
    analyzedFeatureRu: 'Норвежская ERP, проекты, виды работ, учет часов и бухгалтерия',
    investigationGoal: 'Welche Schnittstellen und Datenstrukturen bietet das Zielsystem von ProRiv?',
    investigationGoalRu: 'Какие интерфейсы API и структуры данных предлагает целевая ERP-система ProRiv?',
    observedWorkflow: 'Kaufmännische Verwaltung von Kunden, Projekten und Stunden; Abrechnung und Lohnvorbereitung.',
    observedWorkflowRu: 'Бухгалтерский учет клиентов, проектов и отработанных часов; начисление зарплат и выставление счетов.',
    keyTakeaway: 'Tripletex ist das kaufmännische Nervenzentrum von ProRiv. ISA muss als Ausführungsschicht andocken, nicht konkurrieren.',
    keyTakeawayRu: 'Tripletex — финансовый центр ProRiv. ISA — это мобильный инструмент исполнения на стройке, а не замена ERP.',
    disadvantages: 'Standard-Web/App ist nicht auf spezifische Bohr- und Sägemengen auf der Baustelle optimiert.',
    disadvantagesRu: 'Стандартный веб/приложение Tripletex совершенно не приспособлены для фиксации погонных метров резки и диаметров бурения.',
    sourceOrLink: '',
    transferability: 'Kern des API-Adapters für Stunden- und Stammdatenabgleich.',
    transferabilityRu: 'Ядро нашего адаптера API для синхронизации часов и справочников.',
    origin: 'project_context',
    status: 'technical_verify',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  }
];

export const INITIAL_RESEARCH_FINDINGS: ResearchFinding[] = [
  // USERS
  {
    id: 'f-users-1',
    topicId: 'users',
    title: 'Rollenmodell: Arbeiter, Vorarbeiter, Büro/Admin und Kunde',
    titleRu: 'Модель ролей: Рабочий, Бригадир, Офис/Админ и Заказчик',
    content: 'Kundengespräch: Arbeiter erfassen Arbeitszeiten und Rapporte, senden Rapporte selbst an Kunden. Kunde kann bestätigen, ablehnen, kommentieren. Vorarbeiter kontrolliert Stunden in Tripletex; Buchhaltung nutzt Tripletex. Aufgaben des Vorarbeiters in ISA sind offen.',
    contentRu: 'Из разговора: рабочий учитывает часы и создаёт рапорт, сам отправляет клиенту. Клиент подтверждает, отклоняет, комментирует. Прораб проверяет часы в Tripletex; бухгалтерия тоже работает в Tripletex. Роль прораба в ISA ещё открыта.',
    origin: 'project_context',
    status: 'project_known',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },
  {
    id: 'f-users-2',
    topicId: 'users',
    title: 'Fachliche Trennung: Stundenfreigabe vs. Rapportfreigabe',
    titleRu: 'Разделение процессов: Согласование часов vs Согласование рапорта',
    content: 'KUNDENGESPRÄCH: Arbeiter sendet Rapport selbst an Kunden; Vorarbeiter prüft Stunden in Tripletex. Ob Kundenantwort vor Stundenprüfung erforderlich ist und ob Rapporte intern geprüft werden sollen, bleibt offen. Kein verbindlicher zusätzlicher Rapportfreigabeschritt.',
    contentRu: 'СОГЛАСНО КЛИЕНТУ: рабочий сам отправляет рапорт заказчику, а прораб проверяет часы в Tripletex. Надо уточнить, требуется ли ждать ответа клиента и нужна ли внутренняя проверка рапорта.',
    origin: 'event_storming',
    status: 'recommended',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },
  {
    id: 'f-users-3',
    topicId: 'users',
    title: 'Kundenrolle: Kein permanentes Kundenkonto im MVP nötig',
    titleRu: 'Роль клиента: Постоянный личный кабинет в MVP не нужен',
    content: 'Als schlanke Lösung erhält der Bauleiter/Kunde einen zeitlich begrenzten Magic-Link per SMS oder E-Mail. Er kann den Rapport prüfen, digital abzeichnen oder ablehnen, ohne sich in einem komplexen Portal registrieren zu müssen.',
    contentRu: 'Легкое решение: прораб клиента получает временную ссылку (Magic Link) по SMS или почте. Он может проверить объемы, расписаться или отклонить рапорт без регистрации и паролей.',
    origin: 'architecture_recommendation',
    status: 'recommended',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },

  // CLIENTS
  {
    id: 'f-clients-1',
    topicId: 'clients',
    title: 'Strikte Trennung: Customer → Project → Site',
    titleRu: 'Иерархия сущностей: Заказчик → Проект → Стройплощадка (Site)',
    content: 'Kunde, Projekt und Baustelle (Site) dürfen im Datenmodell nicht vermischt werden. Ein Kunde hat mehrere Projekte; ein Projekt kann mehrere Baustellen/Einsatzorte haben. Nur die konkrete Baustelle (Site) besitzt GPS-Koordinaten und Geofences.',
    contentRu: 'Заказчик, Проект и Площадка не должны сливаться в одну сущность. У заказчика много проектов; у проекта может быть несколько адресов/строек. Только конкретная площадка (Site) имеет координаты и радиус геозоны.',
    origin: 'architecture_recommendation',
    status: 'recommended',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },
  {
    id: 'f-clients-2',
    topicId: 'clients',
    title: 'Eindeutige interne IDs und separate externe Tripletex-IDs',
    titleRu: 'Собственные UUID в системе и внешние Tripletex ID',
    content: 'Alle Entitäten in ISA verwenden eigene UUIDs. Externe Tripletex-IDs werden als separate Zuordnungsfelder gespeichert. So bleibt ISA offline-fähig und unabhängig von ERP-Migrationszyklen.',
    contentRu: 'Все записи в ISA генерируют собственные UUID. Внешние ID Tripletex хранятся как справочные поля. Это дает полную оффлайн-работу и независимость от ERP.',
    origin: 'architecture_recommendation',
    status: 'recommended',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },

  // RAPORT
  {
    id: 'f-raport-1',
    topicId: 'raport',
    title: 'Gewerkespezifische Hauptarbeitsarten für ProRiv',
    titleRu: 'Специализированные операции для ProRiv',
    content: '1. Kernbohren (Bohrdurchmesser mm, Bohrtiefe/Bauteildicke cm, Anzahl, Ausrichtung: Wand / Decke/Bodenplatte / Überkopf).\n2. Bodensäge (Schnitttiefe cm, Schnittlänge m, Anzahl).\n3. Wandsäge / Handsäge (Schnitttiefe cm, Schnittlänge m, Verfahren).',
    contentRu: '1. Алмазное бурение (диаметр мм, глубина/толщина см, количество, ориентация: стена / пол / потолок).\n2. Швонарезчик пола (глубина реза см, длина м, количество).\n3. Стенорезная / ручная пила (глубина реза см, длина м, тип диска).',
    origin: 'project_context',
    status: 'project_known',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },
  {
    id: 'f-raport-2',
    topicId: 'raport',
    title: 'Katalog möglicher Zusatzleistungen & Zuschläge',
    titleRu: 'Каталог дополнительных услуг и наценок',
    content: 'Transport, Baustelleneinrichtung / Rüsten, Hebebühne, Pilotbohrung, Hilfsarbeiter, zusätzliche Regiestunden, Trockenbohren, Granit / Asphalt, Massivholz, starke Bewehrung, Überkopfarbeiten. Pflichtfelder müssen noch mit ProRiv bestätigt werden.',
    contentRu: 'Доставка, развертывание оборудования / монтаж, подъемник, пробное бурение, подсобник, почасовые допработы, сухое бурение, гранит / асфальт, армированный бетон, работы на высоте/потолке. Обязательные поля согласуются с ProRiv.',
    origin: 'project_context',
    status: 'open_decision',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },
  {
    id: 'f-raport-3',
    topicId: 'raport',
    title: 'PriceSnapshot & Revisionslogik',
    titleRu: 'Фиксация цен PriceSnapshot и версионирование ревизий',
    content: 'Ein freigegebener Rapport friert alle Preise im PriceSnapshot ein. Nachträgliche Korrekturen erzeugen eine neue versionierte Revision (WorkReportRevision) mit Audit-Grund. Kein unbemerktes Überschreiben im ERP.',
    contentRu: 'Утвержденный рапорт замораживает все расчеты в снимок цен (PriceSnapshot). Правки задним числом создают новую ревизию с обязательной причиной. Никаких скрытых перезаписей в ERP.',
    origin: 'architecture_recommendation',
    status: 'recommended',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },

  // VREMYA
  {
    id: 'f-vremya-1',
    topicId: 'vremya',
    title: 'Zentrale Architektur-Erkenntnis: Trennung dreier Objekte',
    titleRu: 'Ключевой архитектурный вывод: Разделение трех объектов',
    content: '1. WorkSession: Wann wurde tatsächlich ein- und ausgestempelt? (technische Anwesenheit).\n2. TimesheetEntry: Welche Stunden werden zur Lohnprüfung und Tripletex gemeldet? (Abrechnungszeit).\n3. WorkReport: Welche konkreten Bohr-/Sägearbeiten wurden ausgeführt? (Aufmaß/Leistung).\nDiese drei Objekte dürfen niemals zu einem einzigen Datensatz verschmolzen werden.',
    contentRu: '1. WorkSession: Когда рабочий нажал вход/выход? (физическое присутствие на объекте).\n2. TimesheetEntry: Какие часы подаются в табель зарплаты и Tripletex? (оплачиваемые часы).\n3. WorkReport: Какие конкретно отверстия и метры пропилены? (объем работ для клиента).\nЭти три объекта категорически нельзя объединять в одну запись.',
    origin: 'event_storming',
    status: 'recommended',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },
  {
    id: 'f-vremya-2',
    topicId: 'vremya',
    title: 'GPS-Grundsatz & Ausnahmebehandlung',
    titleRu: 'Принцип использования GPS и обработка сбоев',
    content: 'GPS dient der Plausibilisierung beim Clock-in, nicht als automatische Lohnkürzung oder Dauerüberwachung. Bei fehlendem Signal oder Geofence-Abweichung wird der Clock-in nicht blockiert, sondern ein "ClockInExceptionRecorded"-Event zur Vorarbeiterprüfung erzeugt.',
    contentRu: 'GPS нужен для подтверждения факта прибытия, а не для слежки 24/7 и не для автоматических штрафов. При плохом сигнале вход не блокируется, а создается событие ClockInExceptionRecorded для проверки бригадиром.',
    origin: 'architecture_recommendation',
    status: 'recommended',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },
  {
    id: 'f-vremya-3',
    topicId: 'vremya',
    title: 'Norwegisches Datenschutz- und Arbeitsrecht beachten',
    titleRu: 'Соблюдение норвежского трудового законодательства и приватности',
    content: 'Mitarbeiter-Standortdaten unterliegen strengen norwegischen Datenschutz- und Arbeitsrechtsvorgaben (Datatilsynet). Permanentes Tracking ist unzulässig. Punktuelles Clock-in-GPS muss transparent und rechtlich geprüft sein.',
    contentRu: 'Геолокация сотрудников в Норвегии строго регулируется Datatilsynet. Постоянное фоновое отслеживание запрещено законом. Точечная фиксация координат при чекине должна быть прозрачной и согласованной.',
    origin: 'project_context',
    status: 'open_decision',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },

  // API
  {
    id: 'f-api-1',
    topicId: 'api',
    title: 'Systemlandschaft: AppSheet (Ist) → ISA → Tripletex (ERP)',
    titleRu: 'ИТ-ландшафт: AppSheet (текущий) → ISA (новый) → Tripletex (ERP)',
    content: 'ProRiv nutzt aktuell AppSheet für Rapporte und Tripletex für Buchhaltung und Stunden. ISA ersetzt die AppSheet-Rapporterfassung durch eine moderne maßgeschneiderte Lösung und übergibt freigegebene Daten per Adapter an Tripletex.',
    contentRu: 'Сейчас ProRiv использует AppSheet для рапортов и Tripletex для учета. ISA заменяет неудобный AppSheet специализированным мобильным решением и передает подтвержденные данные через API-адаптер в Tripletex.',
    origin: 'project_context',
    status: 'project_known',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },
  {
    id: 'f-api-2',
    topicId: 'api',
    title: 'Integrationsarchitektur & Idempotenz',
    titleRu: 'Архитектура интеграции и идемпотентность',
    content: 'React Native App → Eigene Work API → PostgreSQL. Tripletex-Adapter mit idempotenten Aufrufen (Idempotency Key). Mehrfaches Senden erzeugt niemals doppelte Stundeneinträge im ERP.',
    contentRu: 'React Native App → Собственный бэкенд Work API → PostgreSQL. Адаптер к Tripletex с ключами идемпотентности. Повторные сетевые запросы никогда не создадут дублей часов в ERP.',
    origin: 'architecture_recommendation',
    status: 'recommended',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },
  {
    id: 'f-api-3',
    topicId: 'api',
    title: 'PDF-Berichte vs. Medienübergabe an Tripletex',
    titleRu: 'PDF-рапорты и передача фото в Tripletex',
    content: 'Es ist noch technisch zu verifizieren, ob Tripletex vollständige Rapport-PDFs und Baustellenfotos per API aufnehmen kann. Vorläufige Empfehlung: Fotos in AWS S3 speichern und Referenz/Link an Tripletex übergeben.',
    contentRu: 'Требуется техническая проверка, может ли API Tripletex сохранять тяжелые бинарные файлы и фото. Предварительное решение: фото в S3, в Tripletex отправляется готовая ссылка.',
    origin: 'project_context',
    status: 'technical_verify',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },

  // MOBILE APP
  {
    id: 'f-app-1',
    topicId: 'mobile-app',
    title: 'Architekturvorgaben aus der Originalskizze: React Native, AWS Cognito, AWS S3',
    titleRu: 'Базовый стек из эскиза сеньора: React Native, AWS Cognito, AWS S3',
    content: 'Die Originalskizze des Seniors spezifiziert ausdrücklich: React Native als Frontend, AWS Cognito für Benutzer- und Sitzungsauthentifizierung sowie AWS Storage S3 für Medien und Fotos. Diese Kerntechnologien bleiben uneingeschränkt erhalten.',
    contentRu: 'Оригинальный эскиз сеньора строго задает стек: React Native на фронтенде, AWS Cognito для авторизации и сессий, AWS Storage S3 для медиа и фото. Все указанные компоненты сохраняются в основе архитектуры.',
    origin: 'sketch',
    status: 'project_known',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },
  {
    id: 'f-app-2',
    topicId: 'mobile-app',
    title: 'Offline-First mit lokaler SQLite & asynchroner Queue',
    titleRu: 'Offline-First на локальной SQLite и асинхронной очереди',
    content: 'Betonbohrer und Säger arbeiten regelmäßig in Tiefgaragen und Kellern ohne Mobilfunknetz. Alle Eingaben werden lokal in SQLite gespeichert und bei Netzrückkehr synchronisiert. Presigned URLs für direkte S3-Uploads.',
    contentRu: 'Бурильщики и пильщики регулярно работают на подземных парковках и в бетонных шахтах без связи. Все данные пишутся локально в SQLite и синхронизируются при появлении интернета. Фото загружаются напрямую в S3 через Presigned URLs.',
    origin: 'architecture_recommendation',
    status: 'recommended',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },
  {
    id: 'f-app-3',
    topicId: 'mobile-app',
    title: 'MVP-Grenzen: Was gehört NICHT in den ersten Release',
    titleRu: 'Границы MVP: Что НЕ входит в первый релиз',
    content: 'Kein vollständiges Bau-ERP, keine Finanzbuchhaltung, keine BIM-3D-Viewer, kein permanentes GPS-Tracking, keine universelle Workflow-Engine, kein Flottenmanagement. Fokus rein auf: Erfassen, Freigeben, Übergeben.',
    contentRu: 'НЕ делаем в первом релизе: тяжелую строительную ERP, бухгалтерию, 3D-BIM вьюеры, постоянный трекинг рабочих, громоздкие движки процессов, учет автопарка. Фокус: зафиксировать работу, согласовать, отправить в Tripletex.',
    origin: 'architecture_recommendation',
    status: 'recommended',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  }
];

export const INITIAL_PRODUCT_RECOMMENDATIONS: ProductRecommendation[] = [
  {
    id: 'rec-users-1',
    topicId: 'users',
    title: 'Serverseitige rollenbasierte Zugriffskontrolle (RBAC)',
    titleRu: 'Серверная ролевая модель доступа (RBAC)',
    description: 'Berechtigungen müssen zwingend auf Backend-Ebene validiert werden. Ausgeblendete Buttons im React-Native-Client stellen keinen Zugriffsschutz dar.',
    descriptionRu: 'Все права и операции проверяются строго на уровне API бэкенда. Скрытие кнопок в интерфейсе React Native не является защитой.',
    rationale: 'Schutz von Preisdaten und Verhinderung von unberechtigten Rapportfreigaben.',
    rationaleRu: 'Защита коммерческих тарифов и гарантия, что рабочие не могут случайно подтверждать рапорты за бригадира.',
    origin: 'architecture_recommendation',
    status: 'recommended',
    priority: 'high',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },
  {
    id: 'rec-clients-1',
    topicId: 'clients',
    title: 'Hierarchische Entitätstrennung: Customer → Project → Site',
    titleRu: 'Иерархическое разделение: Заказчик → Проект → Стройплощадка (Site)',
    description: 'Saubere Datenmodellierung mit separaten UUIDs und getrennter Pflege von Baustellen-Geofences.',
    descriptionRu: 'Четкая модель данных с независимыми UUID и отдельной настройкой геозон для каждой площадки.',
    rationale: 'Kunde, Projekt und Baustelle dürfen für GPS und Tripletex nicht vermengt werden.',
    rationaleRu: 'Заказчик, проект и конкретный объект не должны путаться при сверке геозон и синхронизации с ERP.',
    origin: 'architecture_recommendation',
    status: 'recommended',
    priority: 'high',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },
  {
    id: 'rec-raport-1',
    topicId: 'raport',
    title: 'Statuskette mit Revisionssicherheit & getrennter Kundenprüfung',
    titleRu: 'Жизненный цикл рапорта с ревизиями и внешней ссылкой для клиента',
    description: 'Historischer Vorschlag, NICHT Kundenanforderung: Draft → ForemanApproved → OfficeApproved. Kundengespräch beschreibt stattdessen Arbeiter sendet direkt an Kunden, Kunde bestätigt/lehnt ab; getrennte Stundenprüfung in Tripletex.',
    descriptionRu: 'Историческое предложение (не подтверждено): ForemanApproved и OfficeApproved. Из разговора: рабочий сам отправляет рапорт клиенту; тот подтверждает или отклоняет, часы отдельно проверяют в Tripletex.',
    rationale: 'Verhindert unbemerkte Preisänderungen nach dem Kunden-Review.',
    rationaleRu: 'Исключает незаметные скачки стоимости после того, как заказчик уже подтвердил выполненные объемы.',
    origin: 'architecture_recommendation',
    status: 'recommended',
    priority: 'high',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },
  {
    id: 'rec-vremya-1',
    topicId: 'vremya',
    title: 'Punktuelles Clock-In GPS mit Ausnahmepfad statt Dauerortung',
    titleRu: 'Точечный GPS при чекине с веткой исключений вместо постоянной слежки',
    description: 'Kein Hintergrund-Tracking. GPS nur bei Arbeitsbeginn/Ende prüfen. Bei Abweichung: Eintrag mit Prüfflag für den Vorarbeiter.',
    descriptionRu: 'Никакого фонового трекинга. GPS запрашивается только при нажатии "Старт/Стоп". При неточности — флаг исключения на ручную проверку.',
    rationale: 'Akkuschonend, DSGVO-konform und robust bei Kellereinsätzen.',
    rationaleRu: 'Бережет батарею смартфона, соблюдает европейские нормы и не ломает работу в бетонных подвалах.',
    origin: 'architecture_recommendation',
    status: 'recommended',
    priority: 'high',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },
  {
    id: 'rec-api-1',
    topicId: 'api',
    title: 'Entkopplung von Fachfreigabe und ERP-Exportstatus',
    titleRu: 'Развязка согласования бригадиром и технического экспорта в ERP',
    description: 'Ein Rapport kann fachlich freigegeben sein, während der Tripletex-Export noch ansteht oder fehlgeschlagen ist. Fehlgeschlagener Export darf Freigabe nicht stornieren.',
    descriptionRu: 'Рапорт может быть полностью утвержден бригадиром, даже если отправка в Tripletex еще в очереди или произошел сбой сети. Ошибка API не отменяет утверждение.',
    rationale: 'Verhindert Deadlocks und Inkonsistenzen bei temporären API-Ausfällen.',
    rationaleRu: 'Предотвращает зависания и рассинхронизацию при временной недоступности серверов Tripletex.',
    origin: 'architecture_recommendation',
    status: 'recommended',
    priority: 'high',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },
  {
    id: 'rec-app-1',
    topicId: 'mobile-app',
    title: 'Offline-First Architektur auf React Native + SQLite',
    titleRu: 'Архитектура Offline-First: React Native + SQLite',
    description: 'Lokale Transaktionen auf dem Endgerät mit idempotenter Synchronisation gegen die Work API und direkten S3-Uploads.',
    descriptionRu: 'Локальные транзакции на смартфоне с надежной очередью синхронизации и загрузкой фото в S3.',
    rationale: 'Arbeitsfähigkeit bei unterbrochener Mobilfunkverbindung auf Betonbaustellen.',
    rationaleRu: 'Бесперебойная работа мастеров в подвалах и железобетонных конструкциях без мобильного интернета.',
    origin: 'architecture_recommendation',
    status: 'recommended',
    priority: 'high',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  }
];

export const INITIAL_OPEN_POINTS: OpenPoint[] = [
  {
    id: 'op-vremya-hms-subcontractor',
    topicId: 'vremya',
    additionalTopicIds: ['clients', 'users', 'api'],
    question: 'Senior / Isa: Ist ProRiv hauptsächlich Subunternehmer, Hauptunternehmer oder selbst Bauherr? Wer ist für die elektronische Übersichtsliste zuständig, wer führt sie (ggf. schriftlich delegiert), welches System wird heute genutzt und welche Daten/Schnittstellen werden von ProRiv verlangt?',
    questionRu: 'Сеньор / Иса: ProRiv в основном субподрядчик, генподрядчик или заказчик строительства? Кто отвечает за обязательный электронный список, кто его ведёт (возможна письменная передача), какая система сейчас используется и какие данные/интеграции нужны от ProRiv?',
    clarifyWith: 'senior',
    priority: 'high',
    isResolved: false,
    origin: 'norwegian_compliance_review',
    status: 'open_decision',
    createdAt: '2026-10-09T00:00:00Z',
    updatedAt: '2026-10-09T00:00:00Z'
  },
  {
    id: 'op-users-1',
    topicId: 'users',
    question: 'Darf der Arbeiter oder Vorarbeiter Preise in der mobilen App einsehen oder anpassen?',
    questionRu: 'Может ли рабочий или бригадир видеть коммерческие цены или менять тарифы в мобильном приложении?',
    clarifyWith: 'customer',
    priority: 'high',
    isResolved: false,
    origin: 'project_context',
    status: 'open_decision',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },
  {
    id: 'op-clients-1',
    topicId: 'clients',
    question: 'Ist Tripletex das führende System für Kunden- und Projektstammdaten oder darf ISA Kunden anlegen?',
    questionRu: 'Является ли Tripletex единственной мастер-системой клиентов/проектов или разрешено создавать клиентов прямо в ISA?',
    clarifyWith: 'senior',
    priority: 'high',
    isResolved: false,
    origin: 'project_context',
    status: 'open_decision',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },
  {
    id: 'op-clients-2',
    topicId: 'clients',
    question: 'Wie gehen wir mit Noteinsätzen ohne vorab bekannte Baustellenadresse um?',
    questionRu: 'Как оформлять экстренные аварийные выезды без заранее внесенного адреса площадки?',
    clarifyWith: 'customer',
    priority: 'medium',
    isResolved: false,
    origin: 'project_context',
    status: 'open_decision',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },
  {
    id: 'op-raport-1',
    topicId: 'raport',
    question: 'Muss jeder Rapport zwingend vom Kunden digital gegengezeichnet werden, bevor Stunden abgerechnet werden?',
    questionRu: 'Обязательна ли подпись клиента на рапорте ДО того, как часы пойдут на начисление зарплаты?',
    clarifyWith: 'customer',
    priority: 'high',
    isResolved: false,
    origin: 'event_storming',
    status: 'open_decision',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },
  {
    id: 'op-raport-2',
    topicId: 'raport',
    question: 'Welche genauen Pflichtfelder und Fotos sind für Bohr- und Sägearbeiten zwingend erforderlich?',
    questionRu: 'Какой точный список обязательных полей и фото требуется для бурения и резки?',
    clarifyWith: 'customer',
    priority: 'medium',
    isResolved: false,
    origin: 'project_context',
    status: 'open_decision',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },
  {
    id: 'op-vremya-1',
    topicId: 'vremya',
    question: 'Rechtliche Klärung der norwegischen Datenschutz- und Arbeitsrechtsanforderungen für Clock-In Standortdaten.',
    questionRu: 'Юридическое согласование требований Datatilsynet по фиксации GPS при чекине в Норвегии.',
    clarifyWith: 'customer',
    priority: 'high',
    isResolved: false,
    origin: 'project_context',
    status: 'open_decision',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },
  {
    id: 'op-api-1',
    topicId: 'api',
    question: 'Können vollständige Arbeitsrapport-PDFs und Fotos über die Tripletex-API des ProRiv-Kontos übertragen werden?',
    questionRu: 'Позволяет ли тариф ProRiv в Tripletex прикреплять файлы PDF рапортов и фото напрямую через API?',
    clarifyWith: 'team',
    priority: 'high',
    isResolved: false,
    origin: 'project_context',
    status: 'technical_verify',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },
  {
    id: 'op-app-1',
    topicId: 'mobile-app',
    question: 'Auswahl der AWS-Region für ProRiv (z. B. eu-north-1 Stockholm) und Festlegung der Backup-Aufbewahrungsfristen.',
    questionRu: 'Выбор региона AWS для ProRiv (например, eu-north-1 Стокгольм) и регламент резервного копирования.',
    clarifyWith: 'senior',
    priority: 'medium',
    isResolved: false,
    origin: 'architecture_recommendation',
    status: 'open_decision',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  }
];

export const INITIAL_DECISIONS: Decision[] = [
  {
    id: 'dec-1',
    topicId: 'vremya',
    title: 'Dreiteilung der Zeit- und Leistungsdatenmodelle',
    titleRu: 'Разделение моделей учета времени и выполненных объемов',
    date: '2026-10-08',
    rationale: 'WorkSession (Anwesenheit/Stempeln), TimesheetEntry (Abrechnungsstunden) und WorkReport (Aufmaß/Mengen) werden als eigenständige Entitäten modelliert. Keine Vermischung in einem monolithischen Datensatz.',
    rationaleRu: 'WorkSession (отметка присутствия), TimesheetEntry (оплачиваемые часы табеля) и WorkReport (объемы бурения/резки) разделены на три независимые сущности. Никакого монолитного смешивания.',
    responsiblePerson: 'Senior Software Architect',
    status: 'decided',
    origin: 'event_storming',
    decisionStatus: 'recommended',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },
  {
    id: 'dec-2',
    topicId: 'mobile-app',
    title: 'Beibehaltung der Core-Technologien aus der Originalskizze',
    titleRu: 'Сохранение ключевых технологий из оригинального эскиза',
    date: '2026-10-08',
    rationale: 'Verbindliche Festlegung auf React Native, AWS Cognito und AWS S3 gemäß Skizze des Seniors. Keine stillschweigende Ersetzung durch Dritt-BaaS-Plattformen.',
    rationaleRu: 'Окончательное утверждение React Native, AWS Cognito и AWS S3 строго по эскизу сеньора. Никаких сторонних замен без ведома архитектора.',
    responsiblePerson: 'Senior Software Engineer',
    status: 'decided',
    origin: 'sketch',
    decisionStatus: 'project_known',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  },
  {
    id: 'dec-3',
    topicId: 'api',
    title: 'Entkopplung von Fachfreigabe und ERP-Exportstatus',
    titleRu: 'Разделение утверждения бригадиром и сетевого экспорта в ERP',
    date: '2026-10-08',
    rationale: 'Fachliche Freigaben in ISA sind unabhängig vom Netzwerk- oder Übertragungsstatus der Tripletex-Schnittstelle. Exportjobs laufen asynchron über idempotente Queues.',
    rationaleRu: 'Согласование работ в ISA независимо от статуса сети и доступности Tripletex. Задачи выгрузки выполняются асинхронно через идемпотентную очередь.',
    responsiblePerson: 'Lead Developer',
    status: 'decided',
    origin: 'architecture_recommendation',
    decisionStatus: 'recommended',
    createdAt: '2026-10-08T00:00:00Z',
    updatedAt: '2026-10-08T00:00:00Z'
  }
];
